/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlbumVue: typeof import('./src/components/AlbumVue/AlbumVue.vue')['default']
    ArtistDetail: typeof import('./src/components/ArtistDetail/ArtistDetail.vue')['default']
    ArtistNoiBat: typeof import('./src/components/ArtistNoiBat/ArtistNoiBat.vue')['default']
    AudioList: typeof import('./src/components/AudioList/AudioList.vue')['default']
    BarChart: typeof import('./src/components/BarChart/BarChart.vue')['default']
    CarouselVue: typeof import('./src/components/Carousel/CarouselVue.vue')['default']
    ChatVue: typeof import('./src/components/ChartVue/ChatVue.vue')['default']
    ChillHappyPopular: typeof import('./src/components/ChillHappyPopular/ChillHappyPopular.vue')['default']
    CoOperation: typeof import('./src/components/CoOperation/CoOperation.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EveryDayMusic: typeof import('./src/components/EveryDayMusic/EveryDayMusic.vue')['default']
    LayoutMusics: typeof import('./src/components/LayoutMusics/LayoutMusics.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu/LeftMenu.vue')['default']
    LoadingVue: typeof import('./src/components/customComponents/LoadingVue.vue')['default']
    LoadingVue2: typeof import('./src/components/customComponents/LoadingVue2.vue')['default']
    MainContainer: typeof import('./src/components/MainContainer/MainContainer.vue')['default']
    MainContent: typeof import('./src/components/MainContent/MainContent.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar/MenuBar.vue')['default']
    ModalMV: typeof import('./src/components/ModalMV/ModalMV.vue')['default']
    MusicBeat: typeof import('./src/components/customComponents/MusicBeat.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer/MusicPlayer.vue')['default']
    MVDetail: typeof import('./src/components/MVDetail/MVDetail.vue')['default']
    MVMusic: typeof import('./src/components/MVMusic/MVMusic.vue')['default']
    NavBar: typeof import('./src/components/NavBar/NavBar.vue')['default']
    NewsProduct: typeof import('./src/components/NewsProduct/NewsProduct.vue')['default']
    RadioVue: typeof import('./src/components/RadioVue/RadioVue.vue')['default']
    RipplePlay: typeof import('./src/components/customComponents/RipplePlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/customComponents/Swiper.vue')['default']
    ToolTip: typeof import('./src/components/customComponents/ToolTip.vue')['default']
    Top100Detail: typeof import('./src/components/Top100Detail/Top100Detail.vue')['default']
    TopHundred: typeof import('./src/components/TopHundred/TopHundred.vue')['default']
    TrackList: typeof import('./src/components/TrackList/TrackList.vue')['default']
    VuePerSlide: typeof import('./src/components/VueperSlide/VuePerSlide.vue')['default']
  }
}
