import { OhVueIcon, addIcons } from "oh-vue-icons";
import {
  FaWordpress,
  BiSpotify,
  FaEllipsisH,
  LaBarsSolid ,
  HiSearch,
  BiSearch ,
  CoPlaylistAdd ,
  BiEye ,
  BiHouseDoorFill,
  IoPulseOutline,
  BiBroadcastPin,
  FaMicrophone,
  BiJournalAlbum,
  FaPodcast,
  FaFingerprint,
  RiPulseFill,
  FaPlus,
  MdQueuemusicSharp,
  BiChevronDown ,
  IoTrashSharp,
  HiSolidVolumeUp,
  CoScreenDesktop,
  BiHeadphones,
  BiCheckLg ,
  CoArrowThickTop ,
  CoBarChart ,
  RiArrowUpDownLine ,
  BiPlayBtn ,
  IoSettingsOutline ,
  IoSettingsSharp ,
  CoUserPlus ,
  IoShuffleOutline ,
  IoShuffle ,
  IoShuffleSharp ,
  BiDownload ,
  RiSettings3Line ,
  IoDiamondOutline ,
  IoCloseOutline ,
  LaStar ,
  IoClose ,
  MdDiamondOutlined ,
  BiInfoCircle ,
  FaRegularUser,FaRegularClock,FaHeart,FaRegularHeart ,FaDownload ,FaStepBackward ,FaStepForward ,FaPause ,FaPlay ,FaForward ,FaBackward ,
  FaShareAlt ,LaPlayCircle,BiDiscFill ,FcPrevious  ,MdNavigatenext,MdNavigatebefore ,IoRadioOutline,IoRadio ,BiMusicNote,BiVolumeUpFill  ,BiVolumeMuteFill 
} from "oh-vue-icons/icons";
addIcons(
  FaWordpress,
  BiChevronDown ,
  BiInfoCircle ,
  LaBarsSolid ,
  IoCloseOutline ,
  MdDiamondOutlined ,
  BiDownload ,
  IoDiamondOutline ,
  CoPlaylistAdd ,
  BiEye ,
  IoClose ,
  IoShuffleSharp ,
  IoShuffle ,
  CoUserPlus ,
  BiSearch ,
  LaStar ,
  BiPlayBtn ,
  IoShuffleOutline ,
  BiSpotify,
  FaEllipsisH,
  HiSearch,
  IoSettingsSharp ,
  IoPulseOutline,
  RiArrowUpDownLine ,
  FaPodcast,
  BiHouseDoorFill,
  BiBroadcastPin,
  FaMicrophone,
  BiJournalAlbum,
  FaFingerprint,
  FaPlus,
  RiPulseFill,
  MdQueuemusicSharp,
  IoTrashSharp,
  HiSolidVolumeUp,
  CoScreenDesktop,
  BiHeadphones,
  BiCheckLg ,
  CoBarChart ,
  CoArrowThickTop ,
  RiSettings3Line ,
  IoSettingsOutline,
  FaRegularUser,FaRegularClock,FaHeart ,FaRegularHeart ,FaDownload ,FaStepBackward ,FaStepForward ,FaPause ,FaPlay ,FaForward ,FaBackward ,
  FaShareAlt ,LaPlayCircle ,BiDiscFill ,FcPrevious ,MdNavigatenext ,MdNavigatebefore ,IoRadioOutline,IoRadio ,BiMusicNote,BiVolumeUpFill ,BiVolumeMuteFill 
);
export default OhVueIcon;
